# Name of your application. Used to uniquely configure containers.
service: cam_postal

# Name of the container image (use your-user/app-name on external registries).
image: cam_postal

# Deploy to these servers.
servers:
  web:
    - 5.78.87.254
registry:
  server: localhost:5555
proxy:
  ssl: true
  hosts:
    - cam-postal.gotabs.net
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_ENV: production
    # SOLID_QUEUE_IN_PUMA: true
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
volumes:
  - "cam_postal_storage:/rails/storage"
asset_path: /rails/public/assets


# Configure the image builder.
builder:
  arch: amd64
